<?php

namespace AppBundle\Repository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastInvoiceNumber()
    {
        $lastInvoiceNumber = $this->getEntityManager()->createQueryBuilder()
            ->select('i')
            ->from('AppBundle:Invoice', 'i')
            ->orderBy('i.invoiceNumber', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()

    ;
        if ($lastInvoiceNumber) {
            return $lastInvoiceNumber = $lastInvoiceNumber->getInvoicenumber();
        }

        return $lastInvoiceNumber = '';
    }
}
