app:
    resource: '@AppBundle/Controller/'
    # type: annotation
    # prefix: /%locale%/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /%locale%
    # prefix zo laten staan. Maakt dubbel locale aan in routing, maar werkt wel?!

# invoice:
#     path:     /invoice
#     defaults: { _controller: AppBundle:Invoice:index }
    # prefix: %locale%/
#     requirements:
#         _locale: '%app.locales%'